image: node:20
include:
  - local: .gitlab/docker-release.yml

stages:
  - build
  - release
  - publish

build-monorepo:
  stage: build
  artifacts:
    paths:
      - node_modules/
      - apps/
      - packages/
  cache:
    paths:
      - node_modules/
  script:
    - npm i -g lerna@6.1.0
    - npm install
    - npm run build
    - node pack-apps.mjs

docker-release-admin:
  extends: .service-release
  variables:
    SERVICE_NAME: admin

docker-release-auth:
  extends: .service-release
  variables:
    SERVICE_NAME: auth

docker-release-assets:
  extends: .service-release
  variables:
    SERVICE_NAME: assets

docker-release-content:
  extends: .service-release
  variables:
    SERVICE_NAME: content

docker-release-drafts:
  extends: .service-release
  variables:
    SERVICE_NAME: drafts

docker-release-gateway:
  extends: .service-release
  variables:
    SERVICE_NAME: gateway

docker-release-plugins:
  extends: .service-release
  variables:
    SERVICE_NAME: plugins

docker-release-secrets:
  extends: .service-release
  variables:
    SERVICE_NAME: secrets

docker-release-no-code:
  extends: .service-release
  variables:
    SERVICE_NAME: no-code


deploy_new_managed_version:
  stage: publish
  only:
    - main
  script:
    - >
      curl -H "paunel-user: 63ea478007fe3e002c12649f"
      -H "paunel-script: 64399bc5fef202eb824459b5"
      -H "paunel-token: $PAUNEL_TOKEN"
      -H "paunel-envs: {}" -X GET https://app.paunel.com/api/on/manage-apps/execute