image: node:20
include:
  - local: .gitlab/docker-release.yml

stages:
  - build
  - release

build-monorepo:
  stage: build
  artifacts:
    paths:
      - node_modules/
      - apps/
      - packages/
  cache:
    paths:
      - node_modules/
  script:
    - npm i -g lerna@6.1.0
    - npm install
    - npm run build
    - node pack-apps.mjs

docker-release-admin:
  extends: .service-release
  variables:
    SERVICE_NAME: admin

docker-release-auth:
  extends: .service-release
  variables:
    SERVICE_NAME: auth

docker-release-assets:
  extends: .service-release
  variables:
    SERVICE_NAME: assets

docker-release-content:
  extends: .service-release
  variables:
    SERVICE_NAME: content

docker-release-drafts:
  extends: .service-release
  variables:
    SERVICE_NAME: drafts

docker-release-gateway:
  extends: .service-release
  variables:
    SERVICE_NAME: gateway

docker-release-plugins:
  extends: .service-release
  variables:
    SERVICE_NAME: plugins

docker-release-secrets:
  extends: .service-release
  variables:
    SERVICE_NAME: secrets