apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    version: 1.32.0 (HEAD)
  labels:
    service: admin
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      service: admin
  template:
    spec:
      containers:
        - image: 'registry.gitlab.com/qelos/qelos/admin-panel:main'
          name: admin
      restartPolicy: Always
