apiVersion: v1
kind: Service
metadata:
  annotations:
    version: 1.32.0 (HEAD)
  labels:
    service: admin
  name: admin
spec:
  type: ClusterIP
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
  selector:
    service: admin
