apiVersion: v1
kind: Service
metadata:
  annotations:
    version: 1.32.0 (HEAD)
  labels:
    service: assets
  name: assets
spec:
  type: ClusterIP
  ports:
    - name: "9003"
      port: 9003
      targetPort: 9003
  selector:
    service: assets
