apiVersion: v1
kind: Service
metadata:
  annotations:
    version: 1.32.0 (HEAD)
  labels:
    service: content
  name: content
spec:
  type: ClusterIP
  ports:
    - name: "9001"
      port: 9001
      targetPort: 9001
  selector:
    service: content
