apiVersion: v1
kind: Service
# make it k8s load balancer
metadata:
  annotations:
    version: 1.32.0 (HEAD)
  labels:
    service: gateway
  name: gateway
spec:
  type: LoadBalancer
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    service: gateway
