apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    version: 1.32.0 (HEAD)
  labels:
    service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      service: redis
  template:
    spec:
      containers:
        - image: redis:7.0-alpine
          name: redis
      restartPolicy: Always
