apiVersion: v1
kind: Service
metadata:
  annotations:
    version: 1.32.0 (HEAD)
  labels:
    service: secrets
  name: secrets
spec:
  type: ClusterIP
  ports:
    - name: "9002"
      port: 9002
      targetPort: 9002
  selector:
    service: secrets
