apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  labels:
    app: admin
spec:
  replicas: {{ .Values.admin.replicas }}
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: "{{ .Values.admin.image.repository }}:{{ .Values.admin.image.tag }}"
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: VUE_APP_API_URL
              value: "http://gateway-service"
          resources:
            {{- toYaml $.Values.defaultResources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    app: admin
spec:
  ports:
    - port: {{ .Values.admin.port }}
      targetPort: {{ .Values.admin.port }}
      protocol: TCP
      name: admin-http
  selector:
    app: admin
---
{{- if .Values.admin.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.admin.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-service
                port:
                  number: 80
{{- end }}
