version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - ../apps/db/db-data:/data/db
  redis:
    image: redis:7.0-alpine
    restart: always
  admin:
    extends:
      file: docker-compose.yml
      service: admin
  assets:
    extends:
      file: docker-compose.yml
      service: assets
    depends_on:
      - mongo
      - redis
  auth:
    extends:
      file: docker-compose.yml
      service: auth
    depends_on:
      - mongo
  gateway:
    extends:
      file: docker-compose.yml
      service: gateway
  content:
    extends:
      file: docker-compose.yml
      service: content
    depends_on:
      - mongo
      - redis
  secrets:
    extends:
      file: docker-compose.yml
      service: secrets
    depends_on:
      - mongo
  drafts:
    extends:
      file: docker-compose.yml
      service: drafts
    depends_on:
      - mongo
  plugins:
    extends:
      file: docker-compose.yml
      service: plugins
    depends_on:
      - mongo
      - redis
  no-code:
    extends:
      file: docker-compose.yml
      service: no-code
    depends_on:
      - mongo
      - redis

networks:
  common_network:
