version: '3'
services:
  redis:
    image: redis:7.0-alpine
  admin:
    image: registry.gitlab.com/qelos/qelos/admin-panel:${ADMIN_PANEL_VERSION}
    restart: always
  assets:
    image: registry.gitlab.com/qelos/qelos/assets:${ASSETS_SERVICE_VERSION}
    restart: always
    environment:
      MONGO_URI: ${ASSETS_MONGODB_URI}
      REDIS_URL: redis://redis
      SECRETS_SERVICE_URL: secrets
      SECRETS_SERVICE_PORT: 9002
      AUTH_SERVICE_URL: auth
      SECRETS_TOKEN: ${ASSETS_SECRETS_TOKEN}
      INTERNAL_SECRET: ${INTERNAL_SECRET}
      IP: 0.0.0.0
      SHOW_LOGS: ${SHOW_LOGS}
    depends_on:
      - redis
      - secrets
  auth:
    image: registry.gitlab.com/qelos/qelos/auth:${AUTH_SERVICE_VERSION}
    restart: always
    environment:
      MONGO_URI: ${AUTH_MONGODB_URI}
      IP: 0.0.0.0
      REDIS_URL: redis://redis
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      APPLICATION_URL: ${APPLICATION_URL}
      INTERNAL_SECRET: ${INTERNAL_SECRET}
      SECRETS_TOKEN: ${AUTH_SERVICE_SECRET}
      PLUGINS_SERVICE_URL: plugins
      SECRETS_SERVICE_URL: secrets
      CONTENT_SERVICE_URL: content
      SHOW_LOGS: ${SHOW_LOGS}
    depends_on:
      - secrets
      - redis
  gateway:
    image: registry.gitlab.com/qelos/qelos/gateway:${GATEWAY_VERSION}
    restart: always
    ports:
      - ${PORT}:3000
    environment:
      IP: 0.0.0.0
      REDIS_URL: redis://redis
      BASIC_TENANT: ${BASIC_TENANT}
      APPLICATION_URL: ${APPLICATION_URL}
      INTERNAL_URL: ${INTERNAL_URL}
      CONTENT_SERVICE_URL: content
      AUTH_SERVICE_URL: auth
      ASSETS_SERVICE_URL: assets
      DRAFTS_SERVICE_URL: drafts
      PLUGINS_SERVICE_URL: plugins
      ADMIN_PANEL_URL: admin
      SHOW_LOGS: ${SHOW_LOGS}
  content:
    image: registry.gitlab.com/qelos/qelos/content:${CONTENT_SERVICE_VERSION}
    restart: always
    environment:
      MONGO_URI: ${CONTENT_MONGODB_URI}
      REDIS_URL: redis://redis
      IP: 0.0.0.0
      AUTH_SERVICE_URL: auth
      SHOW_LOGS: ${SHOW_LOGS}
    depends_on:
      - redis
  secrets:
    image: registry.gitlab.com/qelos/qelos/secrets:${SECRETS_SERVICE_VERSION}
    restart: always
    environment:
      MONGO_URI: ${SECRETS_MONGODB_URI}
      IP: 0.0.0.0
      PORT: 9002
      SECRET: ${SECRETS_SERVICE_SECRET}
      INTERNAL_SECRET: ${INTERNAL_SECRET}
      SHOW_LOGS: ${SHOW_LOGS}
  drafts:
    image: registry.gitlab.com/qelos/qelos/drafts:${DRAFTS_SERVICE_VERSION}
    restart: always
    environment:
      MONGO_URI: ${DRAFTS_MONGODB_URI}
      IP: 0.0.0.0
      SHOW_LOGS: ${SHOW_LOGS}
  plugins:
    image: registry.gitlab.com/qelos/qelos/plugins:${PLUGINS_SERVICE_VERSION}
    restart: always
    environment:
      MONGO_URI: ${PLUGINS_MONGODB_URI}
      REDIS_URL: redis://redis
      INTERNAL_SECRET: ${INTERNAL_SECRET}
      SECRETS_TOKEN: ${PLUGINS_SERVICE_SECRET}
      AUTH_SERVICE_URL: auth
      SECRETS_SERVICE_URL: secrets
      IP: 0.0.0.0
      SHOW_LOGS: ${SHOW_LOGS}
    depends_on:
      - redis

networks:
  common_network:
