global:
  showLogs: true
  environment: development
  internalSecret: "no-one-can-access-this-service-without-it"
  redis:
    host: redis://redis-service
    port: 6379
  mongodb:
    # Set to false to use external MongoDB
    deployInCluster: true
    # External MongoDB configuration (used when deployInCluster is false)
    external:
      host: ""
      port: 27017
      database: qelos
    # Internal MongoDB configuration (used when deployInCluster is true)
    internal:
      host: mongodb-service
      port: 27017
      database: qelos

mongodb:
  enabled: true
  image:
    repository: mongo
    tag: latest
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  volumePath: "/Users/davidmeirlevy/dev/qelos/qelos/apps/db/db-data"
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

redis:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

gateway:
  image:
    repository: registry.gitlab.com/qelos/qelos/gateway
    tag: latest
  environment:
    INTERNAL_URL: localhost
    BASIC_TENANT: 0
    APPLICATION_URL: localhost:3000
    SHOW_LOGS: true

auth:
  image:
    repository: registry.gitlab.com/qelos/qelos/auth
    tag: latest
  host: auth-service
  port: 9000
  environment:
    PORT: 9000
    MONGO_URI: mongodb://mongodb-service:27017/qelos
    REDIS_URL: redis://redis-service
    JWT_SECRET: 
    REFRESH_TOKEN_SECRET: 
    SECRETS_TOKEN: auth-service-secret
    PLUGINS_SERVICE_URL: plugins-service
    PLUGINS_SERVICE_PORT: 9003
    SECRETS_SERVICE_URL: secrets-service
    SECRETS_SERVICE_PORT: 9002
    SHOW_LOGS: true

content:
  image:
    repository: registry.gitlab.com/qelos/qelos/content
    tag: latest
  host: content-service
  port: 9001
  environment:
    PORT: 9001
    MONGO_URI: mongodb://mongodb-service:27017/qelos
    REDIS_URL: redis://redis-service
    IP: 0.0.0.0
    AUTH_SERVICE_URL: auth-service
    SHOW_LOGS: true

secrets:
  image:
    repository: registry.gitlab.com/qelos/qelos/secrets
    tag: latest
  host: secrets-service
  port: 9002
  environment:
    MONGO_URI: mongodb://mongodb-service:27017/qelos
    IP: 0.0.0.0
    PORT: 9002
    SECRET: secrets-service-secret
    SHOW_LOGS: true

nocode:
  image:
    repository: registry.gitlab.com/qelos/qelos/no-code
    tag: latest
  host: nocode-service
  port: 9004
  environment:
    MONGO_URI: mongodb://mongodb-service:27017/qelos
    REDIS_URL: redis://redis-service
    SECRETS_TOKEN: 
    AUTH_SERVICE_URL: auth-service
    SECRETS_SERVICE_URL: secrets-service
    SECRETS_SERVICE_PORT: 9002
    PLUGINS_SERVICE_URL: plugins-service
    PLUGINS_SERVICE_PORT: 9003
    PORT: 9004
    SHOW_LOGS: true
    
admin:
  image:
    repository: registry.gitlab.com/qelos/qelos/admin
    tag: latest
  replicas: 2
  ingress:
    enabled: false
  host: admin-service
  port: 3001
  environment:
    PORT: 3001
    MONGO_URI: mongodb://mongodb-service:27017/qelos
    REDIS_URL: redis://redis-service
    AUTH_SERVICE_URL: auth-service
    CONTENT_SERVICE_URL: content-service
    CONTENT_SERVICE_PORT: 9001
    SECRETS_SERVICE_URL: secrets-service
    SECRETS_SERVICE_PORT: 9002
    SHOW_LOGS: true

plugins:
  image:
    repository: registry.gitlab.com/qelos/qelos/plugins
    tag: latest
  host: plugins-service
  port: 9006
  environment:
    PORT: 9006
    MONGO_URI: mongodb://mongodb-service:27017/qelos
    REDIS_URL: redis://redis-service
    SECRETS_TOKEN: plugins-service-secret
    AUTH_SERVICE_URL: auth-service
    SECRETS_SERVICE_URL: secrets-service
    SECRETS_SERVICE_PORT: 9002
    NO_CODE_SERVICE_URL: nocode-service
    NO_CODE_SERVICE_PORT: 9004
    SHOW_LOGS: true

assets:
  image:
    repository: registry.gitlab.com/qelos/qelos/assets
    tag: latest
  replicas: 1
  host: assets-service
  port: 9005
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  environment:
    PORT: 9005
    MONGO_URI: mongodb://mongodb-service:27017/qelos
    REDIS_URL: redis://redis-service
    SECRETS_TOKEN: assets-service-secret
    AUTH_SERVICE_URL: auth-service
    AUTH_SERVICE_PORT: 9000
    SECRETS_SERVICE_URL: secrets-service
    SECRETS_SERVICE_PORT: 9002
    SHOW_LOGS: true

drafts:
  image:
    repository: registry.gitlab.com/qelos/qelos/drafts
    tag: latest
  replicas: 1
  host: drafts-service
  port: 9006
  environment:
    PORT: 9006
    MONGO_URI: mongodb://mongodb-service:27017/qelos
    REDIS_URL: redis://redis-service
    SECRETS_TOKEN: 
    AUTH_SERVICE_URL: auth-service
    AUTH_SERVICE_PORT: 9000
    SECRETS_SERVICE_URL: secrets-service
    SECRETS_SERVICE_PORT: 9002
    SHOW_LOGS: true
    
# Default resource settings for microservices
defaultResources: &defaultResources
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"
