global:
  environment: development
  admin:
    host: admin-service
  redis:
    host: redis-service
    port: 6379
  mongodb:
    # Set to false to use external MongoDB
    deployInCluster: true
    # Connection string for external MongoDB (used when deployInCluster is false)
    connectionString: ""
    # Internal MongoDB configuration (used when deployInCluster is true)
    internal:
      host: mongodb-service
      port: 27017
      database: qelos

mongodb:
  enabled: true
  image:
    repository: mongo
    tag: latest
    pullPolicy: IfNotPresent
  persistence:
    enabled: true
    storageClass: ""
    size: 10Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

gateway:
  image:
    repository: registry.gitlab.com/qelos/qelos/gateway
    tag: latest
  environment:
    INTERNAL_URL: content-service
    CONTENT_SERVICE_URL: content-service
    AUTH_SERVICE_URL: auth-service
    ASSETS_SERVICE_URL: assets-service
    DRAFTS_SERVICE_URL: drafts-service
    PLUGINS_SERVICE_URL: plugins-service
    ADMIN_PANEL_URL: admin-service
    NO_CODE_SERVICE_URL: no-code-service
    REDIS_URL: redis-service
    BASIC_TENANT: default
    APPLICATION_URL: localhost
    SHOW_LOGS: true

auth:
  image:
    repository: registry.gitlab.com/qelos/qelos/auth
    tag: latest
  environment:
    MONGO_URI: mongodb://mongodb-service:27017/qelos
    REDIS_URL: redis-service
    JWT_SECRET: ${JWT_SECRET}
    REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
    APPLICATION_URL: localhost
    INTERNAL_SECRET: ${INTERNAL_SECRET}
    SECRETS_TOKEN: ${AUTH_SERVICE_SECRET}
    PLUGINS_SERVICE_URL: plugins-service
    SECRETS_SERVICE_URL: secrets-service
    CONTENT_SERVICE_URL: content-service
    SHOW_LOGS: true

content:
  image:
    repository: registry.gitlab.com/qelos/qelos/content
    tag: latest
  environment:
    MONGO_URI: mongodb://mongodb-service:27017/qelos
    REDIS_URL: redis-service
    AUTH_SERVICE_URL: auth-service
    SHOW_LOGS: true

secrets:
  image:
    repository: registry.gitlab.com/qelos/qelos/secrets
    tag: latest
  environment:
    MONGO_URI: mongodb://mongodb-service:27017/qelos
    PORT: 9002
    SECRET: ${SECRETS_SERVICE_SECRET}
    INTERNAL_SECRET: ${INTERNAL_SECRET}
    SHOW_LOGS: true

nocode:
  image:
    repository: registry.gitlab.com/qelos/qelos/no-code
    tag: latest
  environment:
    MONGO_URI: mongodb://mongodb-service:27017/qelos
    REDIS_URL: redis-service
    INTERNAL_SECRET: ${INTERNAL_SECRET}
    SECRETS_TOKEN: ${NOCODE_SERVICE_SECRET}
    AUTH_SERVICE_URL: auth-service
    SECRETS_SERVICE_URL: secrets-service
    PLUGINS_SERVICE_URL: plugins-service
    PORT: 9004
    SHOW_LOGS: true
    
admin:
  image:
    repository: registry.gitlab.com/qelos/qelos/admin
    tag: latest
  replicas: 2
  ingress:
    enabled: false
  environment:
    PORT: 80
    MONGO_URI: mongodb://mongodb-service:27017/qelos
    REDIS_URL: redis-service
    AUTH_SERVICE_URL: auth-service
    CONTENT_SERVICE_URL: content-service
    SECRETS_SERVICE_URL: secrets-service
    INTERNAL_SECRET: ${INTERNAL_SECRET}
    SHOW_LOGS: true

plugins:
  image:
    repository: registry.gitlab.com/qelos/qelos/plugins
    tag: latest
  environment:
    MONGO_URI: mongodb://mongodb-service:27017/qelos
    REDIS_URL: redis-service
    INTERNAL_SECRET: ${INTERNAL_SECRET}
    SECRETS_TOKEN: ${PLUGINS_SERVICE_SECRET}
    AUTH_SERVICE_URL: auth-service
    SECRETS_SERVICE_URL: secrets-service
    NO_CODE_SERVICE_URL: no-code-service
    SHOW_LOGS: true

assets:
  image:
    repository: registry.gitlab.com/qelos/qelos/assets
    tag: latest
  replicas: 1
  environment:
    MONGO_URI: mongodb://mongodb-service:27017/qelos
    REDIS_URL: redis-service
    INTERNAL_SECRET: ${INTERNAL_SECRET}
    SECRETS_TOKEN: ${ASSETS_SERVICE_SECRET}
    AUTH_SERVICE_URL: auth-service
    SECRETS_SERVICE_URL: secrets-service
    SHOW_LOGS: true

drafts:
  image:
    repository: registry.gitlab.com/qelos/qelos/drafts
    tag: latest
  replicas: 1
  environment:
    MONGO_URI: mongodb://mongodb-service:27017/qelos
    REDIS_URL: redis-service
    INTERNAL_SECRET: ${INTERNAL_SECRET}
    SECRETS_TOKEN: ${DRAFTS_SERVICE_SECRET}
    AUTH_SERVICE_URL: auth-service
    SECRETS_SERVICE_URL: secrets-service
    SHOW_LOGS: true
    
# Default resource settings for microservices
defaultResources: &defaultResources
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"
