name: Deploy with Helm

on:
  workflow_run:
    workflows: ["Docker Release"]
    types:
      - completed
    branches: [ main ]
  # Add manual trigger capability
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development
      namespace:
        description: 'Kubernetes namespace to deploy to'
        required: false
        default: 'default'
        type: string

jobs:
  # Check if required secrets exist before proceeding
  check-secrets:
    runs-on: ubuntu-latest
    outputs:
      secrets-exist: ${{ steps.check-secrets.outputs.defined }}
    steps:
      - name: Check if secrets exist
        id: check-secrets
        run: |
          # Check if required secrets exist
          if [ -n "$HELM_VALUES" ] && ([ -n "$KUBE_CONFIG" ] || [ -n "$DO_TOKEN" ]); then
            echo "defined=true" >> $GITHUB_OUTPUT
          else
            echo "defined=false" >> $GITHUB_OUTPUT
            echo "::error::Required secrets are not set. You need HELM_VALUES_YAML and either KUBE_CONFIG or DIGITALOCEAN_ACCESS_TOKEN."
          fi
        # Prevent command output from being displayed in logs
        shell: bash {0}
        env:
          # Pass secrets as environment variables
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          DO_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          HELM_VALUES: ${{ secrets.HELM_VALUES_YAML }}

  deploy:
    needs: check-secrets
    # Only run if secrets exist and (workflow was successful or manually triggered)
    if: |
      needs.check-secrets.outputs.secrets-exist == 'true' && 
      (github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    # Set environment to enable protection rules if needed
    environment: ${{ github.event.inputs.environment || 'production' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'
          
      - name: Check for DigitalOcean token
        id: check-do-token
        run: |
          if [ -n "$DO_TOKEN" ]; then
            echo "has_token=true" >> $GITHUB_OUTPUT
          else
            echo "has_token=false" >> $GITHUB_OUTPUT
          fi
        env:
          DO_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Install doctl
        if: steps.check-do-token.outputs.has_token == 'true'
        id: install-doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Verify doctl authentication
        if: steps.check-do-token.outputs.has_token == 'true'
        id: verify-doctl
        run: |
          echo "Verifying DigitalOcean authentication..."
          doctl account get --output json
          if [ $? -ne 0 ]; then
            echo "::error::Failed to authenticate with DigitalOcean. Please check your access token."
            echo "doctl_auth_success=false" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "DigitalOcean authentication successful."
            echo "doctl_auth_success=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Check for KUBE_CONFIG
        id: check-kube-config
        run: |
          if [ -n "$KUBE_CONFIG" ]; then
            echo "has_config=true" >> $GITHUB_OUTPUT
          else
            echo "has_config=false" >> $GITHUB_OUTPUT
          fi
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          
      - name: Set up kubeconfig
        if: (steps.check-do-token.outputs.has_token == 'true' && steps.verify-doctl.outputs.doctl_auth_success == 'true') || steps.check-kube-config.outputs.has_config == 'true'
        env:
          DO_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          DO_CLUSTER_ID: ${{ secrets.DIGITALOCEAN_CLUSTER_ID }}
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          set +x  # Disable command echoing
          umask 077  # Set strict permissions
          mkdir -p $HOME/.kube
          
          # Check if we have DigitalOcean credentials
          if [ -n "$DO_TOKEN" ] && [ -n "$DO_CLUSTER_ID" ]; then
            echo "Using DigitalOcean credentials to access Kubernetes cluster"
            # First verify the cluster exists - with verbose output for debugging
            echo "Verifying DigitalOcean cluster existence..."
            echo "Cluster ID length: ${#DO_CLUSTER_ID}"
            echo "Cluster ID (first 5 chars): ${DO_CLUSTER_ID:0:5}..."
            
            # List all available clusters
            echo "Available clusters:"
            doctl kubernetes cluster list --output json
            
            # Try to get the specific cluster
            echo "Trying to get specific cluster with ID: $DO_CLUSTER_ID"
            doctl kubernetes cluster get "$DO_CLUSTER_ID" --output json || echo "Failed to get cluster with ID: $DO_CLUSTER_ID"
            
            # Now save the kubeconfig with verbose output
            echo "Saving kubeconfig from DigitalOcean..."
            if doctl kubernetes cluster kubeconfig save "$DO_CLUSTER_ID" --set-current-context --verbose; then
              echo "Successfully saved kubeconfig from DigitalOcean"
              kubectl config current-context
            else
              echo "Warning: Failed to get kubeconfig from DigitalOcean using cluster ID"
              
              # Try alternative approach - get the cluster name and use that
              echo "Trying alternative approach using cluster name..."
              CLUSTER_NAME=$(doctl kubernetes cluster list --output json | jq -r '.[0].name')
              
              if [ -n "$CLUSTER_NAME" ]; then
                echo "Found cluster name: $CLUSTER_NAME. Trying to use this instead."
                if doctl kubernetes cluster kubeconfig save "$CLUSTER_NAME" --set-current-context; then
                  echo "Successfully saved kubeconfig using cluster name"
                  kubectl config current-context
                else
                  echo "::error::Failed to get kubeconfig using both cluster ID and name"
                  exit 1
                fi
              else
                echo "::error::No clusters found in DigitalOcean account"
                exit 1
              fi
            fi
          # Otherwise use provided kubeconfig
          elif [ -n "$KUBE_CONFIG" ]; then
            echo "Using provided kubeconfig"
            # Process in memory without echoing to pipes when possible
            if [[ "$KUBE_CONFIG" == *"apiVersion:"* ]]; then
              # Plain text config
              echo "$KUBE_CONFIG" > $HOME/.kube/config
            else
              # Likely base64 encoded
              echo "$KUBE_CONFIG" > $HOME/.kube/config.b64
              base64 -d $HOME/.kube/config.b64 > $HOME/.kube/config 2>/dev/null || cat $HOME/.kube/config.b64 > $HOME/.kube/config
              rm -f $HOME/.kube/config.b64
            fi
          fi
          
          # Ensure config exists before setting permissions
          if [ -f "$HOME/.kube/config" ]; then
            chmod 600 $HOME/.kube/config
          else
            echo "::error::Failed to create kubeconfig file"
            exit 1
          fi
        # Prevent command output from being displayed in logs
        shell: bash {0}
          
      - name: Create values.yaml from secret
        run: |
          set +x  # Disable command echoing
          umask 077  # Set strict permissions
          # Write directly to file to avoid heredoc issues
          HELM_VALUES="${{ secrets.HELM_VALUES_YAML }}"
          echo "$HELM_VALUES" > ./helm/qelos/values.yaml
          chmod 600 ./helm/qelos/values.yaml
          # Verify file was created successfully
          if [ ! -s "./helm/qelos/values.yaml" ]; then
            echo "::error::Failed to create values.yaml file"
            exit 1
          fi
        # Prevent command output from being displayed in logs
        shell: bash {0}
          
      - name: Deploy with Helm
        run: |
          set +x  # Disable command echoing
          # Verify kubeconfig and values.yaml exist before deployment
          if [ ! -f "$HOME/.kube/config" ] || [ ! -s "./helm/qelos/values.yaml" ]; then
            echo "::error::Missing required configuration files"
            exit 1
          fi
          
          # Sanitize namespace input
          NAMESPACE="${{ github.event.inputs.namespace || 'default' }}"
          NAMESPACE="${NAMESPACE//[^a-zA-Z0-9-]/-}"
          
          helm upgrade --install qelos ./helm/qelos \
            --namespace "$NAMESPACE" \
            --create-namespace \
            --atomic \
            --timeout 10m \
            --debug=false \
            --history-max 10
          
          # Don't show detailed error output that might contain secrets
          if [ $? -ne 0 ]; then
            echo "::error::Helm deployment failed"
            exit 1
          fi
        # Prevent command output from being displayed in logs
        shell: bash {0}
